### ISSUE TITLE
audio-coder

### ISSUE THREAD

**Issue by jamen** [audiojs/contributing#12]
Supporting [some different codecs](https://en.wikipedia.org/wiki/List_of_codecs) sounds important for the future plans, like with `audio-batch`.

Could we do these packages like `audio-wav`, `audio-mp3`, etc. with different encode and decode streams that produce or serialize `AudioBuffer`?

**Comment by dfcreative** [comment]
There is awesome [aurora](https://github.com/audiocogs/aurora.js/) framework for mp3 encoding/decoding with js. I guess we could combine codecs to a single _audio-recorder_ or _audio-coder_ or _audio-save_ something like that, to just pass format and that’s it.

**Comment by dfcreative** [comment]
We need _audio-decode_ lib I guess. In browser there is context.decodeAudioData method, but we need that for node.
I saw your audio-decode-wav, which could serve as a part or temporary solution, till we extend to other formats.

**Comment by jamen** [comment]
I have `audio-wav` locally which is unfinished, and is supposed to encode and decode with streams.  Unfortunately the `audio-decode-wav` does not use streams.

**Comment by dfcreative** [comment]
That’s ok, I guess we can provide `audio-decode/stream` for stream version, as it is done in [glsl-parser](https://github.com/stackgl/glsl-parser).

**Comment by dfcreative** [comment]
Hey @jamen I guess we are developing the same thing right now. Can you hold on for a 15 minutes, I will add sketch for browser to the org/npm?

**Comment by jamen** [comment]
Yeah, go for it.  I hadn't started on it yet.

I was going to ask, is this going to be promise-based or stream-based?  I don't know if you are wanting parity with the `decodeAudioData` function.

**Comment by dfcreative** [comment]
So I’ve done a [browser stub](https://github.com/audiojs/audio-decode) for now, the most important and difficult part is up to node...

**Comment by dfcreative** [comment]
@jamen yeah, I’ve added issues to [audio-decode](https://github.com/audiojs/audio-decode/issues). I guess taking care of _Buffers_ is good for node, though Buffer is basically a wrapper for ArrayBuffer. You can use [buffer-to-arraybuffer](https://www.npmjs.com/package/buffer-to-arraybuffer) and [arraybuffer-to-buffer](https://www.npmjs.com/package/arraybuffer-to-buffer) for that, tiny and very performant solutions.

The point is though to try to avoid including _Buffer_ in browserify bundle, because it is huge.

**Comment by dfcreative** [comment]
We should also take care of _audio-encode_ one day for symmetricity?

**Comment by jamen** [comment]
That would be `AudioBuffer` -> `ArrayBuffer`?

**Comment by dfcreative** [comment]
I guess so, yes. _ArrayBuffer_ is the most universal and low-level structure for binary data across platforms

**Comment by jamen** [comment]
Yeah, sounds good to have.  I'll keep that in mind about `Buffer` too.  :+1:
