### ISSUE TITLE
README badges

### ISSUE THREAD

**Issue by jamen** [audiojs/contributing#14]
I can go ahead and add some badges to the READMEs so we can see things like Travis easier.

**Comment by dfcreative** [comment]
I opt for stability and travis badges. Also mb greenkeeper.
Also one day donate)

**Comment by jamen** [comment]
I couldn't find one for greenkeeper, but there is a different thing I have used called david-dm: https://david-dm.org/

**Comment by dfcreative** [comment]
Not sure, it is too long and is not worth support, size or number of dependencies would be better, but not the priority I guess.

**Comment by jamen** [comment]
I don't think we have to add anything except image links for it to work.

For example, here is audio-biquad's without adding anything: ![](https://david-dm.org/audiojs/audio-biquad.svg)

**Comment by dfcreative** [comment]
If you feel like it - let’s go for it.
I just feel like it is more long than meaningful - it is not that important if there is a couple of patches or minor versions in deps, the lib is still in good workable state, and this badge now indicates as if something is broken. That is what we have greenkeeper for now) Also it is bigger than other more meaningful badges, therefore takes attention away from them.

**Comment by jamen** [comment]
Alright, fair enough.  Would be mostly eye candy if we already have greenkeeper.  I'll leave it out.  :p

**Comment by dfcreative** [comment]
Cool, I guess we took that as a practice, travis + stability.
