### ISSUE TITLE
audio-lena

### ISSUE THREAD

**Issue by dfcreative** [audiojs/contributing#16]
There is [lena](https://www.npmjs.com/package/lena) for image testing purposes ([Lenna](https://en.wikipedia.org/wiki/Lenna) in wiki). We need some similar resource for easy audio testing, returning pcm buffer on require.

**Comment by dfcreative** [comment]
https://www.freesound.org/people/heshamwhite/sounds/246148/

**Comment by jamen** [comment]
Sounds good. :D

Do we have to decode the mp3 first though?

**Comment by dfcreative** [comment]
I did that, I am thinking now how to convert to array buffer and add the package. Idk how though to do the first)

**Comment by dfcreative** [comment]
[lena.zip](https://github.com/audiojs/contributing/files/440843/lena.zip)

**Comment by dfcreative** [comment]
Done https://github.com/audiojs/audio-lena
