### ISSUE TITLE
real-time synchronous streams

### ISSUE THREAD

**Issue by ahdinosaur** [audiojs/contributing#18]
hey @audiojs/core @audiojs/devs, thanks for the invite.

i'm Mikey. i do audio / visual programming whenever i feel, i host a local meetup called [Art~Hack Wellington](https://www.facebook.com/groups/714447698702058/), @mmckegg and i collaborate in a [`livejs` org](https://github.com/livejs/), i use [ndarray](https://github.com/scijs/ndarray) as a common data structure between these modules to represent [ndsamples](https://github.com/livejs/ndsamples) or [ndpixels](https://github.com/livejs/ndpixels), and (mostly thanks to Matt playing [Loop Drop](http://loopjs.com/)) it turns out like [this](https://www.youtube.com/watch?v=aIxbJkC9M8k), [this](https://www.youtube.com/watch?v=YkC5Tgv3YaM), or [this](https://www.youtube.com/watch?v=mx6WQgfNha4).

so anyways, why did i make this issue? basically, i like what's happening here, but i have a tiny concern about exporting modules as node streams, because that's what i used to do as well.

why are node streams bad? [a few reasons](http://dominictarr.com/post/145135293917/history-of-streams), most relevant here is that node streams are meant to be asynchronous over many event ticks. this is a problem in my most common use case, where the moment i read a "frame" of audio i want to immediately process it and output pixels to the screen (or LEDs). all of this i want to happen synchronously, because the faster the pixels are displayed the better (enough millisecond delay and everyone will notice it's not "on time", even if subconsciously). even a single `process.nextTick` along the pipeline is wasted time, [zalgo be damned](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony), although i can see y'all have worked around this (set highWaterMark to zero, etc).

what do i recommend instead? so in my modules, i've started doing two things: either a) export a simple function, even if it will commonly be used as a stream. examples: [`pixels-apa102`](https://github.com/livejs/pixels-apa102), [`rainbow-pixels`](https://github.com/ahdinosaur/rainbow-pixels), [`ndsamples-frequencies`](https://github.com/ahdinosaur/ndsamples-frequencies), [`ndpixels-convert`](https://github.com/livejs/ndpixels-convert). or b) export a [`pull-stream`](https://pull-stream.github.io/) which by default are unbuffered synchronous streams (and have [many other benefits](http://dominictarr.com/post/149248845122/pull-streams-pull-streams-are-a-very-simple)). examples: [`read-audio`](https://github.com/livejs/read-audio).

exporting a simple function is nice, because then it's useful for anyone regardless of which stream implementation they favor (@mmckegg uses [`observ`-style observables](https://github.com/mmckegg/mutant) for performance reasons, i want Matt to use my modules :smile:). this is becoming my preference now. exporting a pull stream is nice because it's a consistent interface, handles back-pressure and error propagation very well, can be used synchronously or asynchronously, and [has an vibrant ecosystem](https://pull-stream.github.io/). luckily it's trivial to wrap simple functions as pull streams (using `pull.map`, `pull.infinite`, `pull.drain`, etc).

anyways, lots of text. curious to hear what y'all think. thanks again for the invite. :smiley_cat:

**Comment by jamen** [comment]
So, if I understand correctly: Node streams are good at chunking things for larger amounts of data, but for some usecases (especially in audio) they would be too slow.

I like your idea of using individual synchronous functions, and to some degree I think we already have that with things like [`pcm-util`](https://github.com/audiojs/pcm-util) (and the `*-util` packages in general).  I'm curious to see what @dfcreative thinks about creating more of these maybe.

I still think it is important to support some level of Node streams so they can work inside the ecosystem (i.e. with sockets or `fs` streams), but I'm not against the idea of using `pull-stream` either if there is a nice way to include it.

Your thoughts @dfcreative?

**Comment by ahdinosaur** [comment]
> So, if I understand correctly: Node streams are good at chunking things for larger amounts of data, but for some usecases (especially in audio) they would be too slow.

yes, Node streams buffers data by default and in some cases add unnecessary clock ticks in processing a pipeline of streams (in the worst case each transform adds a clock tick), both are not particularly helpful for a real-time audio use case, but i think possible to workaround as it seems y'all have done. in pull streams this becomes explicit, since the default is unbuffered synchronous streams (waaaaay less magic happening :sparkles:).

> I still think it is important to support some level of Node streams so they can work inside the ecosystem (i.e. with sockets or fs streams)

yep agree, for this we have [`stream-to-pull-stream`](https://github.com/pull-stream/stream-to-pull-stream) and [`pull-stream-to-stream`](https://github.com/pull-stream/pull-stream-to-stream). or there's also [`pull-file`](https://github.com/DamonOehlman/pull-file), [`pull-write-file`](https://github.com/pull-stream/pull-write-file), [`pull-net`](https://github.com/dominictarr/pull-net), or [`pull-ws`](https://github.com/pull-stream/pull-ws) for the same in native pull streams.

**Comment by dy** [comment]
@ahdinosaur oh thanks for the info and links, I appreciate, I’ve read them, very nice!

That delay is indeed bad, and tbh I don’t like how streams perform along with web-audio - occasional glitches etc, but it might be not streams, but syncing, GC etc, _scriptProcessor_ is glitchy regardless of the code we use, I hoped upcoming audio-worker could help with that. Also that might be browserify-caused delays etc, I am going to rewrite [mcjs](https://github.com/dfcreative/mcjs) to get smaller and faster bundles to see.

Some time ago in [audio-through](https://github.com/audiojs/audio-through) or about I had tests of function calls sequence vs raw/object streams and as I got it, streams in flow mode do not necessary cause processor ticks and can be synchronous, actually performance was identical with functions, so I decided that streams were better choice due to conventional API, inheriting Emitter, builtin pressure control etc.

As for pull-stream, zen-observable, rxjs, cycle.js, observable-proposal, etc - there are too many and honestly I am lost. I tried to research, compare, but that was difficult, so I opted for the most standard solution. Actually my hope still is to make as less wrappers and be as less opinionated as possible, in favor of native/polyfill solutions. That is why _AudioBuffer_ :)

I like the idea of function interface and pull-streams, they are definitely worth a try. But I don’t see clearly why streams are bad. With _audio-through_ they are reduced to a single function, which can be sync or async decided by user, in mocha-tests style, (tbh I am not sold on with Zalgo, mocha sync/async API is very nice):

``` js
const Through = require('audio-through');
const Speaker = require('audio-speaker');
const util = require('audio-buffer-utils');

//sync style
Through(buffer => util.fill(buffer, Math.random))
.pipe(Speaker());

//async style
Through((buffer, done) => processOnGPU(buffer, done))
.pipe(Speaker());
```

Async style here is not applicable for realtime, but that might be useful for offline sound rendering, preset-based post-processing, decoding/encoding, network streaming etc.

So I don’t see apparent benefits of pull-streams compared to regular streams in terms of performance here, neither in terms API simplicity, but they are definitely nicer in terms of code simplicity and magic. It needs research/comparison/benchmark.

But that seems reasonable to provide simple function exports for packages, if possible, and a stream wrapper like `audio-*/stream`, as it is done in [audio-decode](https://github.com/audiojs/audio-decode). Not all the modules can be done so though.

So what I would suggest - to hold on any refactoring without tangible digits proving why streams are bad and what is better.

**Comment by dfcreative** [comment]
Alright, I have [read about pull-streams](http://dominictarr.com/), I like the idea, simplicity and possibility to get rid of huge dependencies. Make sense to give a try!

**Comment by dfcreative** [comment]
@ahdinosaur I tried to compose `function generator → volume control → speaker with pressure control` pull-stream, but I can’t wrap thing up in my head.

I have readme example:
```js
//a stream of random numbers.
function source (n) {
	return function (end, cb) {
		if(end) return cb(end)

		//only read n times, then stop.
		if(0 > --n) return cb(true)

		cb(null, Math.random())
	}
}

//volume changer
function through (read, map) {
	//return a readable function!
	return function (end, cb) {
		read(end, function (end, data) {
			cb(end, data != null ? map(data) : null)
		});
	}
}

//read source and log it.
function sink () {
	return function (read) {
		read(null, function next(end, data) {
			if(end === true) return
			if(end) throw end

			console.log(data)
			read(null, next)
		});
	}
}

pull(source, through, sink);
```

What do I do next?

**Comment by dfcreative** [comment]
@ahdinosaur hi, could you help with composing a simple pull-stream `sine generator → volume control → speaker`.
I try to make readme example run and I don’t get it:
```js
const pull = require('pull-stream');

//pull-steam

//a stream of random numbers.
function source (n) {
	return function (end, cb) {
		if(end) return cb(end)

		//only read n times, then stop.
		if(0 > --n) return cb(true)

		cb(null, Math.random())
	}
}

//volume changer
function through (read, map) {
	//return a readable function!
	return function (end, cb) {
		read(end, function (end, data) {
			cb(end, data != null ? map(data) : null)
		});
	}
}

//read source and log it.
function sink () {
	return function (read) {
		read(null, function next(end, data) {
			if(end === true) return
			if(end) throw end

			console.log(data)
			read(null, next)
		});
	}
}

pull(source(), through(), sink());
```
Gives an error.

**Comment by dfcreative** [comment]
@ahdinosaur here is the setup I have for streams https://github.com/dfcreative/stream-contest/blob/gh-pages/stream.js, I want to come up with the same for pull-stream. I thing pull-stream should be better for speaker’s case.

**Comment by ahdinosaur** [comment]
@dfcreative awesome! for most real-world use cases i'd recommend using the helper functions within `pull-stream`:

```js
const pull = require('pull-stream')

//pull-steam

//a stream of random numbers.
function source (n) {
    return pull(
        pull.infinite(Math.random),
        pull.take(n)
    )
}

//volume changer
function through (map) {
    return pull.map(map)
}

//read source and log it.
function sink () {
    return pull.log()
}

pull(source(), through(), sink())
```

you can read those functions' source code for how to do this 'right': [`pull.infinite`](https://github.com/pull-stream/pull-stream/blob/master/sources/infinite.js), [`pull.take`](https://github.com/pull-stream/pull-stream/blob/master/throughs/take.js), [`pull.map`](https://github.com/dominictarr/pull-stream/blob/master/throughs/map.js), [`pull.log`](https://github.com/pull-stream/pull-stream/blob/master/sinks/log.js) (which calls [`pull.drain`](https://github.com/pull-stream/pull-stream/blob/master/sinks/drain.js))

**Comment by ahdinosaur** [comment]
here's a first pass of your `stream-contest`:

```js
const pull = require('pull-stream');
const context = require('audio-context');
const util = require('audio-buffer-utils');

let frameSize = 1024;

function sine () {
  return pull.infinite(function () {
    return util.noise(util.create(frameSize))
  })
}

function volume () {
  return pull.map(function (chunk) {
    util.fill(chunk, v => v * .01);
    return chunk
  })
}

//create speaker routine
function speaker () {
  return function (read) {
    var bufferNode = context.createBufferSource()
    bufferNode.loop = true;
    bufferNode.buffer = util.create(2, frameSize)
    var node = context.createScriptProcessor(frameSize)
    node.addEventListener('audioprocess', function (e) {
      read(null, function (err, data) {
        util.copy(readyData, e.outputBuffer)
      })
    })
    bufferNode.connect(node)
    node.connect(context.destination)
    bufferNode.start()
  }
}

pull(sine(), volume(), speaker())
```

**Comment by dfcreative** [comment]
Alright, some preliminary results show that pull-streams have about 35% less overhead than streams, and ~40% more overhead than plain functions. [stream-contest](https://github.com/dfcreative/stream-contest)

**Comment by dfcreative** [comment]
@ahdinosaur I am trying to add pull-stream-to-stream test, and trying to convert sink stream to node stream, but I can’t wrap my head over it:
```js
let toStream = require('pull-stream-to-stream');
toStream.source(sine).pipe(toStream(volume)).pipe(toStream(speaker));
```
What is the best way to do so?

**Comment by ahdinosaur** [comment]
`toStream` is by default for duplex streams, but also has methods `.source` and `.sink` for readable and writable, respectively.

it looks like `toStream.through` doesn't exist, probably because no reason to implement it yet.

so maybe try:

```js
let toStream = require('pull-stream-to-stream');
toStream.source(sine).pipe(toStream.sink(speaker));
```

**Comment by dfcreative** [comment]
Nope, neither this nor `sine.pipe(volume).pipe(toStream.sink(speaker));` work, where `sine` and `volume` are node streams. Feels like _pull-streams_ don’t really want to be conformist.

Btw @ahdinosaur @mmckegg @jamen could you look at digits in [stream-contest](https://github.com/dfcreative/stream-contest)? I can’t understand their significance, whether refactoring of streams to pull-streams is a good idea for audiojs.

**Comment by jamen** [comment]
Those numbers look good to me and for what I would use this for.  However, I wouldn't mind transitioning for the little added benefit, but only if everyone else wanted to as well.

**Comment by ahdinosaur** [comment]
> Nope, neither this nor sine.pipe(volume).pipe(toStream.sink(speaker)); work, where sine and volume are node streams. Feels like pull-streams don’t really want to be compatible.

hmm, yeah seems like a bug, will want to get that working if we did make this transition.

i think with regards to the benchmarks, a relevant number to compare is much time you have to render each frame given 60 frames per second: 16.67 milliseconds. @dfcreative is a 0.5 ms increase in time per stream in a pipeline or per pipeline? as in, if you had many transform streams in between, would that be an extra 0.5ms per transform?

i really appreciate you all listening and even considering something like a transition to pull streams, but i don't want to add more work on you all if it doesn't feel right. on the flip side if it does feel right i'd like to make it work as best as possible, given my own adoption of pull streams. at the very least, i'm very happy with an outcome of exporting more simple functions that are not tied to a particular stream implementation. :smile:

**Comment by dfcreative** [comment]
One more thing to notice - web-audio-api does not actually care about how long it takes for js to process buffer, it will just spit out the data we managed to put into `outputBuffer`, whatever was it in time or not, and as for node there is a huge buffering in _speaker_ anyways, at least in windows.

But it appears that _stream_ is a bit heavy interface for common use, and pull-streams are hip but without certainty. Basically there is no big difference between the two, it is like left or right hand in theory, the first is just with heritage and the second is with errors/end propagation.

We can place stream implementation to `./stream` and pull-stream to `./pull` files for each component, but what should remain in the `./index.js`?

Many `audio-*` right now use `audio-through` as a dependency, it is possible to make them like:

```js
//audio-smth/stream.js
module.exports = Through(require('./index'));

//audio-smth/pull.js
//through wrapper putting ./index.js in use

//audio-smth - direct processor or constructor of processor (if stateful impl needed)
module.exports = function (buffer, cb) {
util.noise(buffer);
}
```

**Comment by ahdinosaur** [comment]
@dfcreative there are three general types of through streams i'm aware of:

sync map

```
function (buffer) {
  return buffer
}
```

async map

```
function (buffer, cb) {
  cb(null, buffer)
}
```

through (like `through`, `through2`, or `pull-through`). when you want to queue multiple outputs per input and/or push something at the end of a stream. (this could also be done as a flat map: returning a stream in the map and flattening to items)

```
function write (buffer, push) {
  push(buffer)
}

function end (push) {
  push(null)
}
```

either we export the one that makes the most sense and have `audio-through` convert this appropriately to a node stream or export the `through` version or ...?

**Comment by dfcreative** [comment]
audio-through now supports the both sync and async map format, depending on number of arguments. 
If it is possible to make them work well with pull-streams, that is awesome:
```js
module.exports = function (buffer) {
  return buffer; //← not necessary to return btw, enough just modify
}

module.exports = function (buffer, cb) {
  cb(null, buffer);
}

//constructor
module.exports = function (opts) {
  //some state
  this.count = 0;
  return function (buffer, cb?) {
    count++;
    return buffer;
  }
}
```

**Comment by dfcreative** [comment]
It’s alright then? I will give a try with [audio-generator](https://github.com/audiojs/audio-generator). (audio-generate would be a better name though.)

**Comment by ahdinosaur** [comment]
yep exporting a factory function that returns a sync or async map function is perfect. i'm also happy with `./stream` and `./pull` if we want to add stream exports using `./`, although it practice i stopped doing that in favor of just the function exports which i'd wrap myself.

i'll add to my TODO: implement `pull-stream` compatible versions of the following:

- [ ] `audio-speaker` (sink)
- [ ] `web-audio-stream` (sink and source)
- [ ] `audio-generator` (source)
- [ ] `audio-through` (through

this will give us another alternative stream implementation to play with while exporting modules.

although, not sure when i'll do this, since i should be working on a full-time contract at the moment, and am playing with LEDs in my free time :wink: but definitely keen to contribute here!

**Comment by dfcreative** [comment]
Sure, I am glad that we came up with some convention, and actually happy to have more-or-less universal interface for modules. I think to make it main package exports and stream/pull a secondary. Though it will make greenkeeper shit bricks again sorry for today's spam.

**Comment by dfcreative** [comment]
@ahdinosaur btw what is convention for sync end:
```js
function end (buf) {
return null;
}
```
This?

**Comment by ahdinosaur** [comment]
@dfcreative if everything works as either a sync or async map, i'd suggest the convention is to export:

```js
// sync
module.exports = function (options) {
  return function (buffer) {
    return buffer
  }
}

// async
module.exports = function (options) {
  return function (buffer, cb) {
    cb(null, buffer)
  }
}
```

which can be used as node streams in the same way as [`through2-map`](https://www.npmjs.com/package/through2-map) and [`through2-asyncmap`](https://www.npmjs.com/package/through2-asyncmap).

@dfcreative are there use cases that require the more advanced features that `through2` allows for, namely `this.push` of multiple outputs per input or pushing output when the stream has ended?

**Comment by ahdinosaur** [comment]
above comment is for transform / through streams.

for a readable / source stream like `audio-generator`, we'd want something like [`from2`](https://www.npmjs.com/package/from2) but simplified for object streams

```js
// sync source
module.exports = function (options) {
  return function () {
    return buffer
  }
}

// async source
module.exports = function (options) {
  return function (cb) {
    cb(null, buffer)
  }
}
```

**Comment by dfcreative** [comment]
What is the way to end this streams?

There are plans for _audio-splitter_ and _audio-merger_ components, also _audio-mixer_. I am not sure I understand _this.push of multiple outputs per input_, you mean that stream outputs more items than it gets?

**Comment by jamen** [comment]
I think you just return without doing `cb`?

**Comment by ahdinosaur** [comment]
and lastly, for writable / sink streams like `audio-speaker`:

```js
// sync sink
module.exports = function (options) {
  return function (buffer) {
    // do stuff
  }
}

// async sink
module.exports = function (options) {
  return function (buffer, cb) {
    // do stuff
    cb()
  }
}
```

---

> What is the way to end this streams?

what use cases for ending a stream do you have in mind?

so far, for sync functions you can end by throwing an error, for async functions you can end by calling back with an error, but i can imagine the stream wrappers could add external `.abort` (or other named) functions (like [`pull-abortable`](https://www.npmjs.com/package/pull-abortable)) to abort from the outside.

> I am not sure I understand this.push of multiple outputs per input, you mean that stream outputs more items than it gets?

yep, simple example:

```js
const pipe = require('pump')

pipe(
  process.stdin,
  new Transform({
    write: function (chunk, enc, cb) {
      this.push(chunk)
      this.push(chunk)
      cb()
    }
  }),
  process.stdout
)
```

**Comment by dfcreative** [comment]
We need to put this in wiki.

> use cases for ending a stream

E. g. audio-slice, which ends stream after nth second (similar to take in pull-streams).

```js
Generate().pipe(Slice(2)).pipe(Speaker)
```

**Comment by ahdinosaur** [comment]
okay cool. so one important difference between node streams and pull streams is how to signal the _end_.

in node streams, you signal end with `cb(null, null)`. the first slot of the callback is only meant for errors, the second slot is meant for data with the exception of a `null` meaning "the end the stream" (like EOF in unix).

in pull streams, you signal end with `cb(true)`. the first slot of the callback is meant for the end, whether an error or "the end of the stream", which means the second slot is free to have null data.

personally i prefer the latter (`cb(true)` to signal end), but this would be a slight deviation from raw node streams, so we'd have to make our node stream wrappers support this appropriately.

**Comment by dfcreative** [comment]
What if in functional code we just consider returned null-data as an end? It would be similar to sync style where we return null for end:
```js
cb(null, null);
```
It takes a bit of parsing in pull-stream wrapper, though

**Comment by ahdinosaur** [comment]
> What if in functional code we just consider returned null-data as an end?

yeah, i noticed [that's what you are doing already](https://github.com/audiojs/audio-slice/blob/master/index.js#L34-L38), is good with me. :+1:

**Comment by dfcreative** [comment]
Added [wiki](https://github.com/audiojs/contributing/wiki/Streams-convention). Feel free to correct me.
How do we end sink streams? And throwing errors in sync streams - just usual `throw`? Or returning an error?

**Comment by dfcreative** [comment]
@ahdinosaur I’ve refactored [audio-generator](https://github.com/audiojs/audio-generator/blob/master/index.js), so now it exports simple function as `audio-generator/index`, main file is left for `./stream` for now.

I think to make major switch when all components will have pull-streams.

**Comment by ahdinosaur** [comment]
> How do we end sink streams?

i guess return `null` like the other streams? in `pull-stream`, since sinks read from a source (hence the name _pull_ streams, the sinks _pull_ the data from the sources), they end simply by stopping to read from the source. 

> And throwing errors in sync streams - just usual throw? Or return an error?

yeah, i reckon throw errors. personally i'm [experimenting with returning errors](https://github.com/ahdinosaur/mintype), but i think it's far more common to throw. however i could be convinced otherwise, since throwing implies a `catch` which will also catch "programmer errors" (incorrect arguments to a function) which is the problem with promises.

> Tbh if I were to design streams from scratch, I would get rid of 2 args in callback in favor of 

haha, maybe. but what if you _data_ is an error or null? i personally am okay with this separation, hehe.

> @ahdinosaur I’ve refactored audio-generator, so now it exports simple function as audio-generator/index, main file is left for ./stream for now.

woo awesome! :tada:

**Comment by ahdinosaur** [comment]
ah [i see you are returning errors instead of throwing](https://github.com/audiojs/audio-through/commit/8a960718a3def0d2a4a4c30c55c32b4b39c747fa), sweet as :+1:

**Comment by dfcreative** [comment]
I am fine to cast errors and to stick with node convention of 2-arg callbacks, that's just fast fix

**Comment by dfcreative** [comment]
So far I’ve rewritten _audio-generator_, _audio-sink_ and _web-audio-stream_ in functional style, and it feels great.
Somewhat inspired by Crockford’s better js (no self and stuff)). That is one of the best decisions of this year)

**Comment by dfcreative** [comment]
@ahdinosaur I’ve faced an issue during implementing _web-audio-stream/reader_.
The code is the following:
```js
function Reader(options) {
	//...skipped inits
	let node = context.createScriptProcessor(samplesPerFrame, channels, channels);
	let release;
	node.addEventListener('audioprocess', e => {
		let cb = release;
		release = null;
		cb && cb(null, e.inputBuffer);
	});
	return function read (cb) {
		release = cb;
	}
}
```

From outside I call it like so:
```js
let read = Reader();
let count = 0;
read(function getData(err, buffer) {
	if (count++ < 5) {
		read(getData);
	}
	//here we need to end read stream
	else {
	}
});
```
In that case I would follow the usual pull-stream style, just stop reading, but I want also disconnect and dispose the `node`. I don’t see a good way to do that. Feels like I have to use `through`, where I can pass `null` to indicate end.

Also some sources, like _audio-generator_, might actually take already created buffer to fill, instead of creating a new buffer each call. That is a practice to avoid memory churn, e. g. _scriptProcessorNode_ just swaps _inputBuffer_ and _outputBuffer_ instead of creating a new one.

So I would suggest extend sources convention to something like:
```js
// sync source
module.exports = function (options) {
  return function read (buffer?) {
    //return null to end
    return buffer
  }
}

// async source
module.exports = function (options) {
  return function read (buffer?, cb) {
    //cb(null, null) to end
    //cb(error) to throw error
    cb(null, buffer)
  }
}
```
Idk actually, I don’t like the uncertainty of arguments here. But swapping the arguments order to `read(cb, buffer?)` interferes with the rest of API. So I’m puzzled what to do in this case.

**Comment by ahdinosaur** [comment]
@dfcreative great to see your progress. :smiley: 

i like everything you've said above, would be happy with any approach you have in mind.

another option is being able to optionally attach an `.abort(err, cb?)` function to the return value of the constructor (so the `read(cb?)`, `transform(buffer, cb?)`, or `write(buffer, cb?)` functions).

prior art:

- in node streams this is `.close`
- in [`vintage-streams` this is `.destroy`](https://github.com/mafintosh/vintage-streams#readabledestroyerr)
- in [@mmckegg's code using `observ`-style observables this is `.destroy`](https://github.com/mmckegg/loop-drop-app/search?utf8=%E2%9C%93&q=destroy)
- in pull-streams it's common for sink streams to have a `.abort` function attached, plus can be done with [`pull-abortable`](https://github.com/pull-stream/pull-abortable)

**Comment by ahdinosaur** [comment]
> Also some sources, like audio-generator, might actually take already created buffer to fill, instead of creating a new buffer each call. That is a practice to avoid memory churn, e. g. scriptProcessorNode just swaps inputBuffer and outputBuffer instead of creating a new one.

is it possible for `audio-generator` to handle this on it's own? such as by taking a buffer in the constructor to be returned on each read or if no buffer given then creating it's own buffers. in the case of a `scriptProcessorNode` (like your new `web-audio-stream/reader`) the source stream does this within the read function and doesn't need to be passed a buffer, yeah? i'm only wondering if it's possible to keep `read(cb?)` instead of `read(buffer, cb?)`, i ran into this with [audio-generator/pull](https://github.com/audiojs/audio-generator/blob/pull/pull.js).

**Comment by dfcreative** [comment]
Sounds very nice! Agreed about generator.
Glad to know about '.abort' method, it makes for explicity of closing a stream. I would add 'end' method to every of them.

**Comment by dfcreative** [comment]
So I changed generator notation, now `buffer` is optional. Also returned function provides `end` method. (should we call it `close` or `end` is fine?)

**Comment by jamen** [comment]
Nice work :o and `.end` seems good to me.

**Comment by ahdinosaur** [comment]
hey @dominictarr, just wondering: i seem to recall one time you saying you were considering making it part of the pull-stream spec that every sink stream had a `.abort` function; was this real life and if so do you care to unpack the story more for us? thanks. :cat:

**Comment by dominictarr** [comment]
wow, very interesting thread.

First let me clear up a few things. @dfcreative in https://github.com/audiojs/contributing/issues/18#issuecomment-243005149 pull-streams/node-streams compatibility - the problem is currently just converting pull-streams to node-streams. I wrote that module a long time ago, but mostly did it the other way - I converted node-streams to pull-streams with stream-to-pull-stream (which is rock solid) recently people transitioning to pull-streams have found that pull-stream-to-stream had some bugs, but we are fixing those currently.

And single arg: https://github.com/audiojs/contributing/issues/18#issuecomment-243032835 the problem with a single argument is that you then have to use type checking. typechecking in javascript is reliable for primitive types, but because of the way node modules work, you might get two different versions of a module, which can make `instanceof` not work as expected. https://github.com/Gozala/reducers used a single arg pattern, and got into trouble because of it.

@ahdinosaur `pull.drain` already has abort, https://github.com/pull-stream/pull-stream/blob/master/sinks/drain.js#L40-L45 and so any sinks which are implemented via drain. also, if you have a handle on a source stream, you can do `source(true, cb)` to abort.

**Comment by dfcreative** [comment]
@dominictarr https://github.com/audiojs/contributing/issues/18#issuecomment-243005149 is no more a big deal since we decided to provide _pull_ and _stream_ for each audio-component. Btw thanks for _pull-streams_, they are incredibly good!

**Comment by dominictarr** [comment]
oh, awesome!

**Comment by dfcreative** [comment]
So seems we decided on this, other concerns in separate tickets and @ahdinosaur’s list seems to be done, we can close the issue?
