### ISSUE TITLE
ESLint

### ISSUE THREAD

**Issue by dfcreative** [audiojs/contributing#19]
We have to decide and set up code style, mostly to avoid greenkeeper/travis fails.

Things to check:

* strict mode
* no unused variables
* always prefix browser globals with window

Basically anything which may mislead reader.

**Comment by ahdinosaur** [comment]
obligatory [standard](http://standardjs.com).

but honestly [i've learned](https://github.com/pull-stream/pull-stream/issues/52#issuecomment-232244660) it's best left up to those who wrote the code here, which is not me. :smile:

**Comment by dfcreative** [comment]
I would opt for semistandard with tabs, otherwise I feel pain navigating through code and constant dealing with uneven number of spaces in indents, but I don't mind not to force it, even within a single package. Wheres stricts etc wreck greenkeeper, which brings pain to all of us in the case

**Comment by dfcreative** [comment]
Things which I would not check:
* indentation style
* semicolons
* newline at eof
* spaces around fns and conditions
* obligatory block scoping
* anything in comments
*

**Comment by jamen** [comment]
Agreed:  We should have it trigger for bad practices instead of for stylish ones, might be the approach to take.

**Comment by dfcreative** [comment]
Here is `.eslintrc.json` with some rules set to warning instead of error (they can arguably break usual workflow, like running tests etc):

```js
{
    "env": {
        "browser": true,
        "node": true,
        "commonjs": true,
        "es6": true
    },
    "extends": "eslint:recommended",
    "rules": {
        "strict": 1,
        "indent": 0,
        "linebreak-style": 0,
        "quotes": 0,
        "semi": 0,
        "no-cond-assign": 1,
        "no-constant-condition": 1,
        "no-duplicate-case": 1,
        "no-empty": 1,
        "no-ex-assign": 1,
        "no-extra-boolean-cast": 1,
        "no-extra-semi": 1,
        "no-fallthrough": 1,
        "no-func-assign": 1,
        "no-inner-declarations": 1,
        "no-irregular-whitespace": 1,
        "no-mixed-spaces-and-tabs": 1,
        "no-redeclare": 1,
        "no-unused-vars": 1,
        "no-sparse-arrays": 1
    }
}
```

Which other rules should we add?

**Comment by dfcreative** [comment]
If we're agreed on that `.eslintrc.json`, we can close this issue.

**Comment by jamen** [comment]
Yup, agree on those rules.  Nice work.  :)
