### ISSUE TITLE
Using `assert` + `unassertify`

### ISSUE THREAD

**Issue by jamen** [audiojs/contributing#39]
I've seen a neat pattern in modules to use asserts to verify types and do more fine debugging:

```js
function something (options) {
  assert.equal(typeof options, 'object', 'options must be an object')
  // ...
}
```

This way you get friendly errors in development, then you use something like [`unassertify`](https://www.npmjs.com/package/unassertify) in production to strip all the validation away and get smaller bundles.

One downside is that we do have to tell users to remove the asserts or else their bundle sizes will be a bit larger...  I do not think this is too huge of a deal.

**Comment by dfcreative** [comment]
Yes, looks like a nice pattern, the approach of _choo_. Although assert is not elaborated much, eg. sometimes need to do something like
```js
if (!(a instanceof ArrayBuffer)) throw Error('arg should be an array buffer')
```
It really depends on component and use case I think, it is easy to fall into covering imaginary wrong arguments instead of minimal checks. But in general I am for.

**Comment by dfcreative** [comment]
@jamen I use assertions [here](https://github.com/audiojs/web-audio-write/blob/master/index.js#L24), feels good :)

**Comment by jamen** [comment]
@dfcreative Yup looks good to me.  :smile_cat:

**Comment by connorhartley** [comment]
I will also apply this to speaker to replace the debug module. I'll cook it in with the many other formatting fixes I want to make.

**Comment by dfcreative** [comment]
That seems to be good option for browser, but is there a good way to disable assertions for node?

**Comment by jamen** [comment]
@dfcreative Hmm that is a great point.  Is there something bad about having the asserts in production with node?

**Comment by dfcreative** [comment]
Recently I had [short discussion](https://github.com/compute-io/contributing/issues/2) on that, basically we can detect ifs with single throw statement statically, so there is no much need in unassertify at all.

**Comment by jamen** [comment]
Okay, I like the sound of that better, so I was checking in. assert was not as good in retrospect.
