### ISSUE TITLE
audio-format module

### ISSUE THREAD

**Issue by dy** [audiojs/contributing#41]
In [pcm-convert](https://github.com/audiojs/pcm-convert) stumbled upon pretty useful and easy to read/write format notation, that turns out also to be pretty performant. That can be extended to any _audio-*_ component and solve [the problem of indicating desired data input/output format](https://github.com/audiojs/contributing/issues/36).

That is just a plain string with tags, like so:
```js
'interleaved uint8 le stereo 44100'
'stereo audiobuffer 96000'
```
Note how natural they are to read.

To parse that, we just split by `\s+` and match keywords. For sample rate we can use [sample-rate](https://github.com/audiojs/sample-rate) package. For custom formats, like 5 channels, we can use an old-school object `{channels: 5, ...}`.

That allows to shrink API of many components to just:
```js
createOscillator({
type: 'sine',
frequency: (t) => t + 440,
format: 'float32 mono 44100'
})
```
With that can easily use all `audio-*` components with any thinkable audio data type.

**Comment by jamen** [comment]
I saw that in your package and I thought it was really cool! I also had thought about a hypothetical `atype` package today.  Great idea.  :smile:

**Comment by dfcreative** [comment]
@jamen I guess we may need _audio-convert_ package then, to be able to convert _AudioBuffer_ ←→ _*_

**Comment by dfcreative** [comment]
Alright, [audio-format](https://github.com/audiojs/audio-format) package.
