### ISSUE TITLE
awesome JS audio list

### ISSUE THREAD

**Issue by derhuerst** [audiojs/contributing#42]
I've stumbled upon a few robust-looking, nicely scoped, tested npm modules that I'd like to see as more discoverable.

**What about adding a list of "awesome JS audio" modules**, with a strict requirement of "small scope, tested"? I'm asking because it doesn't sound feasible to convince, yet alone contact, each author and ask them wether they would like to transfer their project to `audiojs`.

**Comment by dfcreative** [comment]
:+1:

Although to convince authors to transfer their projects that would take better org maintenance, docs and working infrastructure, that is why we are waiting. Personally I think _audio_, _web-audio-api_ and _audio-speaker_ are the three milestone components need finishing before making any marketing efforts, although I may be wrong.

**Comment by connorhartley** [comment]
This seems like a good idea to me and I agree @dfcreative we need to get those modules sorted.

**Comment by derhuerst** [comment]
We can also collect project to invite to `audiojs` in the future.

- [`supported-audio`](https://github.com/ArtskydJ/supported-audio) – Returns the best supported audio type for your browser of the types you provide
- [`ffmpeg-static`](https://github.com/eugeneware/ffmpeg-static) – ffmpeg static binaries for Mac OSX and Linux and Windows

**Comment by dfcreative** [comment]
@derhuerst actually that sounds nice! You want to get started? Some extended to non-audiojs modules catalogue is nice idea!

**Comment by derhuerst** [comment]
@dfcreative Sure! What about `audiojs/awesome`? do you think the repo should convey the purpose even without the org's name? `audiojs/awesome-js-audio`?

**Comment by dfcreative** [comment]
I'd go for 'audiojs/awesome-audio[js]' or 'audiojs/awesome-modules', ie. repo name should convey the full name of the list, regardless of the org. It is SEO-friendly and better conveys the sense of URL. Also cloning that repo would create just 'awesome' folder, which is meaningless.

**Comment by derhuerst** [comment]
But then `awesome-modules` is also not very helpful. `awesome-audio-js` is helpful but claims ownership in a way. `awesome-audio-modules` does not, but is missing the info that these are JS modules.

**Comment by dfcreative** [comment]
Hmm makes sense. Let it be just `audiojs/awesome` then for now maybe, we can rename it at any time?

**Comment by dfcreative** [comment]
Although I like `awesome-audiojs` - we don't claim ownership, instead, we highlight our friends and take care of some audio-related components, which have their own authors.

**Comment by derhuerst** [comment]
Would like to go with `awesome-audio-js` then, as `awesome-audiojs` sounds to me as if we selected the best modules from the `audiojs` org (which is not entirely true).

**Comment by dfcreative** [comment]
@derhuerst let's first list these modules mb and then decide on name? For now we can pick any name

**Comment by derhuerst** [comment]
done: audiojs/awesome-audiojs

**Comment by derhuerst** [comment]
what's the status of https://github.com/audio-lab/awesome ?

**Comment by dfcreative** [comment]
@derhuerst I removed it
