### ISSUE TITLE
CI and greenkeeper

### ISSUE THREAD

**Issue by dfcreative** [audiojs/contributing#6]
Ideally we should come up with CI (travis is good) and greenkeeper set up for all components.

**Comment by jamen** [comment]
How should I create the `travis.yml` file?  Dependencies in some project tests' aren't there by default.

I think we could tailor each configuration different depending on the package, or we could add all necessary packages to `devDependencies` and optionally use something like [`pnpm`](https://github.com/rstacruz/pnpm) to avoid the repeated CLI downloads and duplicate packages in general.

**Comment by jamen** [comment]
I got this setup, it's just a matter of fixing some the component's tests now.
